spring:
  application:
    name: user-experience-service
  datasource:
    url: jdbc:mysql://localhost:3306/recommendation_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  flyway:
    enabled: true
    validate-on-migrate: true

server:
  port: 8090

app:
  purchase-history:
      limit: 100
      category-limit: 5
  max-recommend-count: 100


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html
  pathsToMatch: /api/recommendations/**
